SELECT REF(S)
FROM TB_SALA S
WHERE S.ID = 101; 

-- Usando DEREF para acessar os detalhes da relacionamento ternário a partir da referência
SELECT DEREF(P.DETENTO).nome AS PRESIDIARIO, 
       DEREF(P.ALA) AS localizacao
FROM TB_POSSUI P;

-- Acessando os elementos do VARRAY
SELECT C.TIPO, t.COLUMN_VALUE AS CELAS
FROM TB_CELA C,
     TABLE(C.CELAS) t;


SELECT F.nome, T.COLUMN_VALUE AS TELEFONES
FROM TB_FUNCIONARIO F,
     TABLE(F.TELEFONES) T;
--Os detentos e aonde estão
SELECT d.CPF, d.NOME, d.DATA_NASC, d.COMPORTAMENTO, a.ID AS ALA_ID, c.ID AS CELA_ID, c.TIPO AS TIPO_CELA
FROM TB_DETENTO d
JOIN TB_POSSUI p ON p.DETENTO = REF(d)
JOIN TB_ALA a ON p.ALA = REF(a)
JOIN TB_CELA c ON p.CELA = REF(c);

--As alas e suas celas
SELECT a.ID AS ALA_ID, a.TIPO, a.CAPACIDADE, COUNT(c.COLUMN_VALUE) AS QTD_CELAS
FROM TB_ALA a
JOIN TABLE(a.CELAS) c
GROUP BY a.ID, a.TIPO, a.CAPACIDADE;

--Todos os visitantes de um detento
SELECT v.VISITANTE.CPF AS CPF_VISITANTE, VI.NOME AS NOME_VISITANTE, v.DATA_HORA, d.CPF AS CPF_DETENTO, d.NOME AS NOME_DETENTO
FROM TB_VISITA v
JOIN TB_VISITANTE VI ON v.VISITANTE.CPF = VI.CPF
JOIN TB_DETENTO d ON v.DETENTO = REF(d);

--Sentenças e crimes
SELECT s.DETENTO.CPF AS CPF_DETENTO, d.NOME AS NOME_DETENTO, s.DURACAO AS DURACAO_SENTENCA, c.ID_CRIME, c.DURACAO AS DURACAO_CRIME
FROM TB_SENTENCA s
JOIN TB_DETENTO d ON s.DETENTO = REF(d)
JOIN TB_CRIME c ON s.CRIME = REF(c);
