SELECT REF(S)
FROM TB_SALA S
WHERE S.ID = 101; 

-- Usando DEREF para acessar os detalhes da relacionamento ternário a partir da referência
SELECT DEREF(P.DETENTO).nome AS PRESIDIARIO, 
       DEREF(P.ALA) AS localizacao
FROM TB_POSSUI P;

-- Acessando os elementos do VARRAY
SELECT C.TIPO, t.COLUMN_VALUE AS CELAS
FROM TB_CELA C,
     TABLE(C.CELAS) t;


SELECT F.nome, T.COLUMN_VALUE AS TELEFONES
FROM TB_FUNCIONARIOS F,
     TABLE(F.TELEFONES) T;
--Os detentos e aonde estão
SELECT d.CPF, d.NOME, d.DATA_NASC, d.COMPORTAMENTO, a.ID AS ALA_ID, c.ID AS CELA_ID, c.TIPO AS TIPO_CELA
FROM TB_DETENTO d
JOIN TB_POSSUI p ON p.DETENTO = REF(d)
JOIN TB_ALA a ON p.ALA = REF(a)
JOIN TB_CELA c ON p.CELA = REF(c);

--As alas e suas celas
SELECT a.ID AS ALA_ID, a.TIPO, a.CAPACIDADE, COUNT(c.COLUMN_VALUE) AS QTD_CELAS
FROM TB_ALA a
JOIN TABLE(a.CELAS) c
GROUP BY a.ID, a.TIPO, a.CAPACIDADE;

--Todos os visitantes de um detento
SELECT v.VISITANTE.CPF AS CPF_VISITANTE, VI.NOME AS NOME_VISITANTE, v.DATA_HORA, d.CPF AS CPF_DETENTO, d.NOME AS NOME_DETENTO
FROM TB_VISITA v
JOIN TB_VISITANTE VI ON v.VISITANTE.CPF = VI.CPF
JOIN TB_DETENTO d ON v.DETENTO = REF(d);

--Sentenças e crimes
SELECT s.DETENTO.CPF AS CPF_DETENTO, d.NOME AS NOME_DETENTO, s.DURACAO AS DURACAO_SENTENCA, c.ID_CRIME, c.DURACAO AS DURACAO_CRIME
FROM TB_SENTENCA s
JOIN TB_DETENTO d ON s.DETENTO = REF(d)
JOIN TB_CRIME c ON s.CRIME = REF(c);


-- Todas as entradas feitas em um intervalo de tempo, incluindo informações sobre o detento, o visitante, e a sala onde a entrada foi registrada.
SELECT DEREF(E.DETENTO).NOME AS NOME_DETENTO,
       DEREF(E.DETENTO).CPF AS CPF_DETENTO,
       DEREF(E.VISITANTE).NOME AS NOME_VISITANTE,
       DEREF(E.VISITANTE).CPF AS CPF_VISITANTE,
       E.DATA_HORA,
       DEREF(L.SALA).DESCRICAO AS LOCAL_ENTRADA
FROM TB_ENTRADA E
JOIN TB_LOCAL L ON E.DATA_HORA = L.DATA_HORA
WHERE E.DATA_HORA BETWEEN TO_DATE('2024-09-16', 'YYYY-MM-DD') AND TO_DATE('2024-09-17', 'YYYY-MM-DD')
ORDER BY E.DATA_HORA DESC;

-- Todos os endereços e contar quantos funcionários, guardas e diretores estão associados a cada endereço.
SELECT E.CEP,
       E.RUA,
       E.BAIRRO,
       (SELECT COUNT(*) FROM TB_FUNCIONARIOS F WHERE F.ENDERECO.CEP = E.CEP) AS NUM_FUNCIONARIOS,
       (SELECT COUNT(*) FROM TB_GUARDA G WHERE G.ENDERECO.CEP = E.CEP) AS NUM_GUARDAS,
       (SELECT COUNT(*) FROM TB_DIRETOR D WHERE D.ENDERECO.CEP = E.CEP) AS NUM_DIRETORES
FROM TB_ENDERECO E
ORDER BY NUM_FUNCIONARIOS DESC, NUM_GUARDAS DESC, NUM_DIRETORES DESC;

-- Detalhes dos diretores que têm funcionários com salários superiores a R$10.000, incluindo o nome do diretor e os nomes dos funcionários.
SELECT DEREF(S.DIRETOR).NOME AS NOME_DIRETOR,
       F.NOME AS NOME_FUNCIONARIO,
       F.SALARIO
FROM TB_SUPERINTENDENTE S
JOIN TB_FUNCIONARIOS F ON DEREF(S.DIRETOR).CPF = F.CPF
WHERE F.SALARIO > 10000
ORDER BY F.SALARIO DESC;

-- Relação de guardas que trabalham no mesmo turno que seus supervisores e o total de guardas supervisionados por cada supervisor.
SELECT G.NOME AS NOME_GUARDA,
       DEREF(G.SUPERVISOR).NOME AS NOME_SUPERVISOR,
       G.TURNO AS TURNO_GUARDA,
       (SELECT COUNT(*) FROM TB_GUARDA G2 WHERE DEREF(G2.SUPERVISOR).CPF = DEREF(G.SUPERVISOR).CPF) AS TOTAL_SUPERVISIONADOS
FROM TB_GUARDA G
WHERE G.TURNO = DEREF(G.SUPERVISOR).TURNO
ORDER BY TOTAL_SUPERVISIONADOS DESC;

-- Todos os superintendentes e o valor total do salário incluindo bonificação, mostrando também o nome do diretor ao qual estão associados.
SELECT S.NOME AS NOME_SUPERINTENDENTE,
       S.SALARIO,
       S.BONIFICACAO,
       (S.SALARIO + S.BONIFICACAO) AS SALARIO_TOTAL,
       DEREF(S.DIRETOR).NOME AS NOME_DIRETOR
FROM TB_SUPERINTENDENTE S
ORDER BY SALARIO_TOTAL DESC;

-- Todas as entradas realizadas em cada sala, incluindo a quantidade de entradas por sala em um determinado dia.
SELECT DEREF(L.SALA).ID AS ID_SALA,
       DEREF(L.SALA).DESCRICAO AS NOME_SALA,
       COUNT(E.DATA_HORA) AS NUM_ENTRADAS
FROM TB_LOCAL L
JOIN TB_ENTRADA E ON L.DATA_HORA = E.DATA_HORA
WHERE E.DATA_HORA BETWEEN TO_DATE('2024-09-16', 'YYYY-MM-DD') AND TO_DATE('2024-09-17', 'YYYY-MM-DD')
GROUP BY DEREF(L.SALA).ID, DEREF(L.SALA).DESCRICAO
ORDER BY NUM_ENTRADAS DESC;
