-- TABELA DE TELEFONES *****************
CREATE TABLE TB_TELEFONES (
    CONSTRAINT pk_telefones PRIMARY KEY (CPF_FUNCIONARIO, NUMERO),
    CONSTRAINT fk_telefones_funcionario FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES TB_FUNCIONARIOS(CPF)
);

-- TABELA DE ENDEREÇOS ok
CREATE TABLE TB_ENDERECO OF TP_ENDERECO (
    CEP PRIMARY KEY
);

-- TABELA DE FUNCIONÁRIOS ok
CREATE TABLE TB_FUNCIONARIOS OF TP_FUNCIONARIO (
    CONSTRAINT pk_funcionario PRIMARY KEY (CPF)
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES;


-- TABELA DE DIRETORES OK
CREATE TABLE TB_DIRETOR OF TP_DIRETOR (
    CPF PRIMARY KEY
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES_DIRETOR;


-- TABELA DE GUARDA OK
CREATE TABLE TB_GUARDA OF TP_GUARDA (
    CPF PRIMARY KEY
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES_GUARDA;

-- TABELA DE SUPERINTENDENTES

CREATE TABLE TB_SUPERINTENDENTE OF TP_SUPERINTENDENTE (
    CPF PRIMARY KEY,
    DIRETOR WITH ROWID REFERENCES TB_DIRETOR,
    CONSTRAINT CHECK_SEXO2 CHECK (SEXO IN ('F', 'M'))
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES_SUPERINTENDENTE;

-- TABELA DE LISTA_DE_CELAS (?)
CREATE TABLE TB_LISTA_DE_CELAS (
    ID NUMBER PRIMARY KEY,
    CELULAS LISTA_DE_CELAS
);

-- TABELA DE ALAS ok
CREATE TABLE TB_ALA OF TP_ALA (
    ID PRIMARY KEY
);

-- TABELA DE DETENTOS ok
CREATE TABLE TB_DETENTO OF TP_DETENTO (
    CPF PRIMARY KEY
);

-- Criação da tabela Visita com SCOPE IS
CREATE TABLE TB_VISITA OF TP_VISITA (
    DETENTO SCOPE IS TB_DETENTO -- Garante que o REF para detento é da tabela Detento
);
/

-- TABELA DE CELAS ok
CREATE TABLE TB_CELA OF TP_CELA (
    ID PRIMARY KEY
);

-- TABELA DE POSSUI OK
CREATE TABLE TB_POSSUI OF TP_POSSUI (
    PRIMARY KEY (ID_POSSUI)
);

-- TABELA DE TIPOS DE CELAS ok
CREATE TABLE TB_TIPO_CELA OF TP_TIPO_CELA (
    TIPO_CELA PRIMARY KEY
);

-- TABELA DE SALAS ok
CREATE TABLE TB_SALA OF TP_SALA (
    ID PRIMARY KEY
);

-- TABELA DE VISITANTES ok
CREATE TABLE TB_VISITANTE OF TP_VISITANTE (
    CPF PRIMARY KEY
);

-- TABELA DE ENTRADAS OK
CREATE TABLE TB_ENTRADA OF TP_ENTRADA (
    DATA_HORA PRIMARY KEY
);

-- TABELA DE LOCAIS OK
CREATE TABLE TB_LOCAL OF TP_LOCAL (
    DATA_HORA PRIMARY KEY
);
 
-- TABELA DE CRIMES ok
CREATE TABLE TB_CRIME OF TP_CRIME (
    ID_CRIME PRIMARY KEY
);

-- TABELA DE SENTENÇAS OK
CREATE TABLE TB_SENTENCA OF TP_SENTENCA (
    DURACAO PRIMARY KEY
);


