-- TABELA DE TELEFONES *****************
CREATE TABLE TB_TELEFONES OF TELEFONES_NESTED (
    COLUMN_VALUE VARCHAR2(15) -- CHECAR
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES;

-- TABELA DE ENDEREÇOS ok
CREATE TABLE TB_ENDERECO OF TP_ENDERECO (
    CEP PRIMARY KEY
);

-- TABELA DE FUNCIONÁRIOS ok
CREATE TABLE TB_FUNCIONARIOS OF TP_FUNCIONARIO (
    CONSTRAINT pk_funcionario PRIMARY KEY (CPF)
) NESTED TABLE TELEFONES STORE AS TB_TELEFONES;


-- TABELA DE DIRETORES
CREATE TABLE TB_DIRETOR OF TP_DIRETOR (
    CPF PRIMARY KEY
);

-- TABELA DE GUARDA
CREATE TABLE TB_GUARDA OF TP_GUARDA (
    CPF PRIMARY KEY
);

-- TABELA DE SUPERINTENDENTES
CREATE TABLE TB_SUPERINTENDENTE OF TP_SUPERINTENDENTE (
    CPF PRIMARY KEY
);

-- TABELA DE LISTA_DE_CELAS (?)
CREATE TABLE TB_LISTA_DE_CELAS OF LISTA_DE_CELAS ();

-- TABELA DE ALAS ok
CREATE TABLE TB_ALA OF TP_ALA (
    ID PRIMARY KEY
);

-- TABELA DE DETENTOS ok
CREATE TABLE TB_DETENTO OF TP_DETENTO (
    CPF PRIMARY KEY
);

-- Criação da tabela Visita com SCOPE IS
CREATE TABLE TB_VISITA OF TP_VISITA (
    DETENTO SCOPE IS TB_DETENTO -- Garante que o REF para detento é da tabela Detento
);
/

-- TABELA DE CELAS ok
CREATE TABLE TB_CELA OF TP_CELA (
    ID PRIMARY KEY
);

-- TABELA DE POSSUI
CREATE TABLE TB_POSSUI OF TP_POSSUI (
    DETENTO PRIMARY KEY REFERENCES TB_DETENTO(CPF),
    ALA PRIMARY KEY REFERENCES TB_ALA(ID),
    CELA PRIMARY KEY REFERENCES TB_CELA(ID)
);

-- TABELA DE TIPOS DE CELAS ok
CREATE TABLE TB_TIPO_CELA OF TP_TIPO_CELA (
    TIPO_CELA PRIMARY KEY
);

-- TABELA DE SALAS ok
CREATE TABLE TB_SALA OF TP_SALA (
    ID PRIMARY KEY
);

-- TABELA DE VISITANTES ok
CREATE TABLE TB_VISITANTE OF TP_VISITANTE (
    CPF PRIMARY KEY
);

-- TABELA DE ENTRADAS
CREATE TABLE TB_ENTRADA OF TP_ENTRADA (
    DETENTO PRIMARY KEY REFERENCES TB_DETENTO(CPF),
    VISITANTE PRIMARY KEY REFERENCES TB_VISITANTE(CPF),
    DATA_HORA PRIMARY KEY
);

-- TABELA DE LOCAIS
CREATE TABLE TB_LOCAL OF TP_LOCAL (
    DATA_HORA PRIMARY KEY,
    SALA REFERENCES TB_SALA(ID)
);
 
-- TABELA DE CRIMES ok
CREATE TABLE TB_CRIME OF TP_CRIME (
    ID_CRIME PRIMARY KEY
);

-- TABELA DE SENTENÇAS
CREATE TABLE TB_SENTENCA OF TP_SENTENCA (
    DETENTO PRIMARY KEY REFERENCES TB_DETENTO(CPF),
    CRIME PRIMARY KEY REFERENCES TB_CRIME(ID_CRIME)
);


