-- ENDEREÇO

CREATE OR REPLACE TYPE TP_ENDERECO AS OBJECT (
    CEP VARCHAR2(8),
    RUA VARCHAR2(30),
    NUMERO NUMBER,
    BAIRRO VARCHAR2(20),

    CONSTRUCTOR FUNCTION TP_ENDERECO(SELF IN OUT NOCOPY TP_ENDERECO, CEP VARCHAR2, RUA VARCHAR2, NUMERO NUMBER, BAIRRO VARCHAR2) RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY TP_ENDERECO AS
    CONSTRUCTOR FUNCTION TP_ENDERECO(SELF IN OUT TP_ENDERECO, CEP VARCHAR2, RUA VARCHAR2, NUMERO NUMBER, BAIRRO VARCHAR2) RETURN SELF AS RESULT IS
        BEGIN
            SELF.CEP := CEP; SELF.RUA := RUA;
            SELF.NUMERO := NUMERO; SELF.BAIRRO := BAIRRO;
            RETURN;
        END;
END;
/


-- FUNCIONÁRIO

CREATE OR REPLACE TYPE TP_FUNCIONARIO AS OBJECT (
    CPF VARCHAR2(11),
    NOME VARCHAR2(50),
    DATA_NASC DATE,
    SEXO CHAR(1),
    DATA_ADM DATE,
    ENDERECO TP_ENDERECO,
    SALARIO NUMBER
) NOT FINAL NOT INSTANTIABLE;
/


-- DIRETOR (ESPECIALIZAÇÃO)

CREATE OR REPLACE TYPE TP_DIRETOR UNDER TP_FUNCIONARIO (
    DATA_INICIO DATE
    -- ADICIONAR CONSTRUTOR
);
/


-- SUPERINTENDENTE (ESPECIALIZAÇÃO)

CREATE OR REPLACE TYPE TP_SUPERINTENDENTE UNDER TP_FUNCIONARIO (
    BONIFICACAO NUMBER,
    DIRETOR REF TP_DIRETOR
    -- ADICIONAR CONSTRUTOR
);
/


-- GUARDA (ESPECIALIZAÇÃO)

CREATE OR REPLACE TYPE TP_GUARDA UNDER TP_FUNCIONARIO (
    TURNO VARCHAR2(5),
    SUPERVISOR REF TP_GUARDA
    -- ADICIONAR CONSTRUTOR
);
/


-- DETENTO

CREATE OR REPLACE TYPE TP_DETENTO AS OBJECT ( 
    CPF VARCHAR2(11), 
    NOME VARCHAR2(30),
    DATA_NASC DATE,
    SEXO CHAR(1),
    DATA_ENT DATE,
    COMPORTAMENTO VARCHAR2(30),

    CONSTRUCTOR FUNCTION TP_DETENTO(SELF IN OUT NOCOPY TP_DETENTO, CPF VARCHAR2, NOME VARCHAR2, DATA_NASC DATE, SEXO CHAR, DATA_ENT DATE, COMPORTAMENTO VARCHAR2) RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY TP_DETENTO AS
	CONSTRUCTOR FUNCTION TP_DETENTO(SELF IN OUT TP_DETENTO, CPF VARCHAR2, NOME VARCHAR2, DATA_NASC DATE, SEXO CHAR, DATA_ENT DATE, COMPORTAMENTO VARCHAR2) RETURN SELF AS RESULT IS
		BEGIN
			SELF.CPF := CPF; SELF.NOME := NOME; SELF.DATA_NASC := DATA_NASC;
			SELF.SEXO := SEXO; SELF.DATA_ENT := DATA_ENT; SELF.COMPORTAMENTO := COMPORTAMENTO;
			RETURN SELF;
		END;
END;
/


-- SENTENÇA

CREATE OR REPLACE TYPE TP_SENTENCA AS OBJECT (
    CRIME VARCHAR2(30),
    DETENTO REF TP_DETENTO,
    DURACAO NUMBER
    -- ADICIONAR CONSTRUTOR
);
/


-- ALA

CREATE OR REPLACE TYPE TP_ALA AS OBJECT (
    ID NUMBER,
    TIPO VARCHAR2(10),
    CAPACIDADE NUMBER
    -- ADICIONAR CONSTRUTOR
);
/


-- CELA

CREATE OR REPLACE TYPE TP_CELA AS OBJECT (
    ID NUMBER,
    TIPO VARCHAR2(10),
    SEGURANCA VARCHAR2(10)
    -- ADICIONAR CONSTRUTOR
);
/


-- SALA DE VISITAS

CREATE OR REPLACE TYPE TP_SALA AS OBJECT (
    ID NUMBER
    -- ADICIONAR CONSTRUTOR
);
/


-- VISITANTE

CREATE OR REPLACE TYPE TP_VISITANTE AS OBJECT (
    CPF VARCHAR2(11),
    NOME VARCHAR2(50),
    DATA_NASC DATE,
    SEXO CHAR(1)
    -- ADICIONAR CONSTRUTOR
);
/


-- ENTIDADE ASSOCIATIVA DETENTO-VISITANTE

CREATE OR REPLACE TYPE TP_DETENTO_VISITANTE AS OBJECT (
    DETENTO REF TP_DETENTO,
    VISITANTE REF TP_VISITANTE,
    MOTIVO_VISITA VARCHAR2(20),
    DATA_VISITA DATE,
    SALA REF TP_SALA
    -- ADICIONAR CONSTRUTOR
);
/


-- POSSUI (RELACIONAMENTO TRIPLO ENTRE DETENTO-ALA-CELA)

CREATE OR REPLACE TYPE TP_POSSUI AS OBJECT (
    DETENTO TP_DETENTO,
    ALA TP_ALA,
    CELA TP_CELA
    -- ADICIONAR CONSTRUTOR
);
/