-- TABELA DE DIRETORES

CREATE TABLE TB_DETENTO_TABLE OF TP_DETENTO(
    PRIMARY KEY (CPF),
    OBJECT IDENTIFIER IS PRIMARY KEY
);

-- TABELA FUNCIONARIOS
CREATE TABLE TB_FUNCIONARIOS OF TP_FUNCIONARIO(
    PRIMARY KEY (CPF),
    OBJECT IDENTIFIER IS PRIMARY KEY
);


-- TABELA DE SUPERINTENDENTES

CREATE TABLE TB_SUPERINTENDENTE OF TP_SUPERINTENDENTE (
    CPF PRIMARY KEY,
    DIRETOR WITH ROWID REFERENCES TB_DIRETOR,
    CONSTRAINT CHECK_SEXO2 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE GUARDAS

CREATE TABLE TB_GUARDA OF TP_GUARDA (
    CPF PRIMARY KEY,
    SUPERVISOR WITH ROWID REFERENCES TB_GUARDA,
    CONSTRAINT CHECK_SEXO3 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE DETENTOS

CREATE TABLE TB_DETENTO OF TP_DETENTO (
    CPF PRIMARY KEY,
    CONSTRAINT CHECK_SEXO4 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE SENTENÇAS

CREATE TABLE TB_SENTENCA OF TP_SENTENCA (
    DETENTO WITH ROWID REFERENCES TP_DETENTO,
    PRIMARY KEY (DETENTO, CRIME),
    CONSTRAINT CHECK_DURACAO CHECK (DURACAO BETWEEN 1 AND 30)
);

-- TABELA DE VISITA

CREATE TABLE TB_VISITA OF TP_VISITA(
    PRIMARY KEY (CPF),
    OBJECT IDENTIFIER IS PRIMARY KEY
);

-- TABELA POSSUI

CREATE TABLE TB_POSSUI OF TP_POSSUI(
    PRIMARY KEY (ROWID), -- PRIMARY KEY pode ser ROWID ou um identificador único se houver.
    OBJECT IDENTIFIER IS PRIMARY KEY
);

-- TABELA CRIME

CREATE TABLE TB_CRIME OF TP_CRIME(
    PRIMARY KEY (ID_CRIME),
    OBJECT IDENTIFIER IS PRIMARY KEY
);

-- TABELA VISITANTE

CREATE TABLE TB_VISITANTE OF TP_VISITANTE(
    PRIMARY KEY (ID_CRIME),
    OBJECT IDENTIFIER IS PRIMARY KEY
);


