-- TABELA DE DIRETORES

CREATE TABLE TB_DIRETOR OF TP_DIRETOR (
    CPF PRIMARY KEY,
    CONSTRAINT CHECK_SEXO CHECK (SEXO IN ('F', 'M'))
);


-- TABELA DE SUPERINTENDENTES

CREATE TABLE TB_SUPERINTENDENTE OF TP_SUPERINTENDENTE (
    CPF PRIMARY KEY,
    DIRETOR WITH ROWID REFERENCES TB_DIRETOR,
    CONSTRAINT CHECK_SEXO2 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE GUARDAS

CREATE TABLE TB_GUARDA OF TP_GUARDA (
    CPF PRIMARY KEY,
    SUPERVISOR WITH ROWID REFERENCES TB_GUARDA,
    CONSTRAINT CHECK_SEXO3 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE DETENTOS

CREATE TABLE TB_DETENTO OF TP_DETENTO (
    CPF PRIMARY KEY,
    CONSTRAINT CHECK_SEXO4 CHECK (SEXO IN ('F', 'M'))
);
/


-- TABELA DE SENTENÇAS

CREATE TABLE TB_SENTENCA OF TP_SENTENCA (
    DETENTO WITH ROWID REFERENCES TP_DETENTO,
    PRIMARY KEY (DETENTO, CRIME),
    CONSTRAINT CHECK_DURACAO CHECK (DURACAO BETWEEN 1 AND 30)
);
